#!/usr/bin/env python3

import sys

arguments = sys.argv

if len(arguments) < 2:
    print("Usage: little <string to be converted> ")
    sys.exit(1)

def string_to_little_endian(name):
    # Reverse the input string and convert it to hexadecimal format
    little_endian_hex = ''.join([f'\\x{name[i:i+2]}' for i in range(0, len(name), 2)][::-1])
    return little_endian_hex

for arg in arguments[1:]:
    print(string_to_little_endian(arg))

